# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mav_sim.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'mav_sim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmav_sim.proto\x12\x07mav_sim\"\r\n\x0bInfoRequest\"T\n\x0cInfoResponse\x12\x0f\n\x07vehicle\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07\x64ialect\x18\x03 \x01(\t\x12\x11\n\tsystem_id\x18\x04 \x01(\r\"\x10\n\x0eMissionRequest\"b\n\x0bMissionItem\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\r\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x05 \x01(\x01\"E\n\x0fMissionResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12#\n\x05items\x18\x02 \x03(\x0b\x32\x14.mav_sim.MissionItem\",\n\x10TelemetryRequest\x12\x18\n\x10interval_seconds\x18\x01 \x01(\x01\"e\n\x0ePositionUpdate\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01\x12\x0f\n\x07reached\x18\x05 \x01(\x08\x32\xcd\x01\n\x06MavSim\x12\x36\n\x07GetInfo\x12\x14.mav_sim.InfoRequest\x1a\x15.mav_sim.InfoResponse\x12?\n\nGetMission\x12\x17.mav_sim.MissionRequest\x1a\x18.mav_sim.MissionResponse\x12J\n\x12SubscribeTelemetry\x12\x19.mav_sim.TelemetryRequest\x1a\x17.mav_sim.PositionUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mav_sim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INFOREQUEST']._serialized_start=26
  _globals['_INFOREQUEST']._serialized_end=39
  _globals['_INFORESPONSE']._serialized_start=41
  _globals['_INFORESPONSE']._serialized_end=125
  _globals['_MISSIONREQUEST']._serialized_start=127
  _globals['_MISSIONREQUEST']._serialized_end=143
  _globals['_MISSIONITEM']._serialized_start=145
  _globals['_MISSIONITEM']._serialized_end=243
  _globals['_MISSIONRESPONSE']._serialized_start=245
  _globals['_MISSIONRESPONSE']._serialized_end=314
  _globals['_TELEMETRYREQUEST']._serialized_start=316
  _globals['_TELEMETRYREQUEST']._serialized_end=360
  _globals['_POSITIONUPDATE']._serialized_start=362
  _globals['_POSITIONUPDATE']._serialized_end=463
  _globals['_MAVSIM']._serialized_start=466
  _globals['_MAVSIM']._serialized_end=671
# @@protoc_insertion_point(module_scope)
