# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mav_sim_pb2 as mav__sim__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mav_sim_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MavSimStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/mav_sim.MavSim/GetInfo',
                request_serializer=mav__sim__pb2.InfoRequest.SerializeToString,
                response_deserializer=mav__sim__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.GetMission = channel.unary_unary(
                '/mav_sim.MavSim/GetMission',
                request_serializer=mav__sim__pb2.MissionRequest.SerializeToString,
                response_deserializer=mav__sim__pb2.MissionResponse.FromString,
                _registered_method=True)
        self.SubscribeTelemetry = channel.unary_stream(
                '/mav_sim.MavSim/SubscribeTelemetry',
                request_serializer=mav__sim__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=mav__sim__pb2.PositionUpdate.FromString,
                _registered_method=True)


class MavSimServicer:
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Static identity/build info for the simulated vehicle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMission(self, request, context):
        """Latest uploaded mission (the same view as GET /api/mission).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeTelemetry(self, request, context):
        """Server-streamed telemetry: one PositionUpdate per simulated waypoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MavSimServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=mav__sim__pb2.InfoRequest.FromString,
                    response_serializer=mav__sim__pb2.InfoResponse.SerializeToString,
            ),
            'GetMission': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMission,
                    request_deserializer=mav__sim__pb2.MissionRequest.FromString,
                    response_serializer=mav__sim__pb2.MissionResponse.SerializeToString,
            ),
            'SubscribeTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTelemetry,
                    request_deserializer=mav__sim__pb2.TelemetryRequest.FromString,
                    response_serializer=mav__sim__pb2.PositionUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mav_sim.MavSim', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mav_sim.MavSim', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MavSim:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mav_sim.MavSim/GetInfo',
            mav__sim__pb2.InfoRequest.SerializeToString,
            mav__sim__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mav_sim.MavSim/GetMission',
            mav__sim__pb2.MissionRequest.SerializeToString,
            mav__sim__pb2.MissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mav_sim.MavSim/SubscribeTelemetry',
            mav__sim__pb2.TelemetryRequest.SerializeToString,
            mav__sim__pb2.PositionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
